apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-03-23T10:36:43Z"
  generation: 1
  labels:
    run: nginx
    tier: frontend
    type: app1
  name: nginx
  namespace: default
  resourceVersion: "82215"
  uid: 1e6555b2-66f3-4106-a867-d96922fc0eb0
spec:
  containers:
  - image: nginx
    name: nginx
  nodeName: cka-cluster3-worker


    