apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /var/www/html
      volumes:
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: local-pvc
  replicas: 3
  selector: 
    matchLabels: 
      env: demo


